apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cm-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-cm-demo
  template:
    metadata:
      labels:
        app: nginx-cm-demo
    spec:
      volumes:
      - name: config                      #volumes的名称
        configMap:
          name: nginx-conf                #指定使用ConfigMap的名称
          items:
          - key: nginx.conf
            path: nginx.conf
            mode: 0644
          - key: www.conf
            path: www.conf
            mode: 0644
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config                    #指定上面的volumes名称
          mountPath: "/etc/app1"   #容器挂载的目录
          #subPath: nginx.conf

